Traceback (most recent call last):
  File "/home/user/webapp/web_server.py", line 22, in <module>
    main()
  File "/home/user/webapp/web_server.py", line 16, in main
    with socketserver.TCPServer(('0.0.0.0', PORT), MyHandler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/web_server.py", line 22, in <module>
    main()
  File "/home/user/webapp/web_server.py", line 16, in main
    with socketserver.TCPServer(('0.0.0.0', PORT), MyHandler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/web_server.py", line 22, in <module>
    main()
  File "/home/user/webapp/web_server.py", line 16, in main
    with socketserver.TCPServer(('0.0.0.0', PORT), MyHandler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/web_server.py", line 22, in <module>
    main()
  File "/home/user/webapp/web_server.py", line 16, in main
    with socketserver.TCPServer(('0.0.0.0', PORT), MyHandler) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
